### ISSUE TITLE
Trying to understand Anti-Deadzone, Linearity?

### ISSUE THREAD

**Issue by Shaolinmonk123** [KrossX/Durazno#18]
Hi, thanks for all the hard work. 

I'm trying to use Durazno with one game in particular. BLUR. Its a racing game and I believe that the developers hard coded a significant deadzone into the games controls making it hard to use a steering wheel. I put durazno into the game folder then swapped some buttons around to be sure it was working and it was... Then I increased the anti deazone slider. Oddly it seemed to help when pushing the analog stick to the right but not to the left? My only real test is I'm just barley nudging the stick to the right and it engages but there's a good 1/8" of travel before it engages to the left... I'm wondering if I should be playing with the linearity slider, but I don't really know what that does... Also are the any advanced ways to configure the anti-deadzone setting?

Thanks

**Comment by KrossX** [comment]
I don't know how the wheel rotation works in actual numbers so maybe something weird is going on. Anti-deadzone should've worked to any side since by default it works by modifying the radius of the stick. Maybe it would be better for the wheel to enable the LinearADZ checkbox. There's a test tab that you can use to check the effect of the changes.

Anti-deadzone just jumpstarts the initial values so that a nudge overcomes the game's deadzone. Linearity on the other hand can make the initial movement less sensitive which can help with making subtle movements easier and the other way around with a negative linearity.

Just make sure to be using the latest build and check the test tab to see how your changes affect input.

**Comment by Shaolinmonk123** [comment]
Thanks so much for the info, really appreciate it.

**Comment by KrossX** [comment]
Surething, it's the Readme: [http://tiny.cc/magicaltools](http://tiny.cc/magicaltools)
Points to a Google Drive folder.

**Comment by Shaolinmonk123** [comment]
Beautiful, thank you.
