### ISSUE TITLE
{Question] About Foreground / Background Programs

### ISSUE THREAD

**Issue by shinra358** [KrossX/Durazno#19]
Would it be possible for you to code in the ability to check in a checkbox for this program to only allow input to the game that you're playing If it is in the foreground? The reason I ask is because a guy made a custom launcher that's better than the game's launcher but it has a bug that the launcher still recieves input when playing the game, causing the game to keep launching itself. The guy has been mia for months now. 

Is this at all possible to do with durazno?

**Comment by KrossX** [comment]
Durazno only alters input when the application requests it. Possible to do what you ask? Sure, in the "anything is possible" kind of way. However, it would be better to use another method to hack that launcher instead of messing up Durazno for that.

There's also the possibility that it would be faster and easier to just make a new launcher than spending time figuring out how to hackfix something.

**Comment by shinra358** [comment]
Making a script that freezes the launcher process only when the game window is running seems to suffice. I guess that's good enough : P
