### ISSUE TITLE
Host releases on Github

### ISSUE THREAD

**Issue by 07416** [KrossX/Durazno#22]
Upload compiled releases to Github. Also, please remove the URL shortener `tiny.cc`.

**Comment by KrossX** [comment]
Any reason to dislike the tiny.cc ? I'll check about how to use releases anyway though.

**Comment by 07416** [comment]
@KrossX I and many, many others dislike URL shortener links in general.

**Comment by shadow7412** [comment]
He asked for a *reason* why you dislike tiny.cc. Saying you 'dislike them in general' helps no-one.

But the usual reason people tend to dislike them, is because they hide what the url is. This is a pretty common tactic for people who are linking to malware to use, as you can't see what site you are going to until it's too late.

**Comment by KrossX** [comment]
I understand the dislike, though I started using it because the google drive url is just plain ugly. My previous public folder was on mediafire but that site was most likely to contain malware from its many ads. Anyhow, I could change the shortener for the google drive url for now if that helps. 

As for using Releases as a hosting method, it's kind of problematic for me as it requires proper use of tags (which are wrong in all my projects) as opposed to just dropping files.

**Comment by shadow7412** [comment]
Another option is to change your readme file to a readme.md file - then you can use github's markup to avoid having to show the full url on the screen. That way security conscious people can still have a look before clicking and people who don't care don't have to...

**Comment by KrossX** [comment]
The readme is included in the zip file, so I would rather keep it a simple text file.

**Comment by rdoeffinger** [comment]
While proper tags would be a bonus (and you can create them ad-hoc when doing the release), you can instead just create a "dummy"/"all_releases"/whatever tag and release and upload all your binaries on that one.
I don't think that would end up much worse than the Google drive interface, and in some ways better.

**Comment by KrossX** [comment]
Done! It's been some time ain't it.
