### ISSUE TITLE
Cannot download from Google Drive

### ISSUE THREAD

**Issue by vMeijin** [KrossX/Durazno#28]
Google prevents the download and states, that the files contain a virus. This applies to all versions.

**Comment by KrossX** [comment]
Somehow it seems zipped Durazno is a trojan... =_="

https://www.virustotal.com/en/file/5dce4f610ae1f59bef663aedf1f7c7d03deb61437e4a9bb6e17449096e632585/analysis/1482775351/

I unzipped the files and ClamAV didn't complain, rezipped with Windows' instead of 7zip and it also complained about a trojan. If I use 7z instead, no problem. *sighs*

**Comment by vMeijin** [comment]
Thanks, it works now.
