### ISSUE TITLE
After removal, every EXE creates a durazno.ini.

### ISSUE THREAD

**Issue by Kiesman** [KrossX/Durazno#47]
The program seems to be lingering _somewhere_ on my computer after removing it. No matter what I do, I get an INI added when I launch games, and it crashes certain games.

**Comment by garoto** [comment]
Did you copied Durazno's own `xinput1_3.dll` wrapper DLL to your somewhere in your path? Like `C:\Windows\System32`?

**Comment by Kiesman** [comment]
Yes but I removed it once I realized it didn't help

**Comment by garoto** [comment]
Reinstall the `directx` redistributive.

**Comment by Kiesman** [comment]
That worked, thanks

**Comment by KrossX** [comment]
Thanks @garoto!

@Kiesman : Durazno is just wrapper that the game must load instead of the system file so that it can then load it itself and modify its behavior. So the system file is quite necessary for things to work and should not be replaced. That's why Durazno is meant to be used at the game's directory and no the system's.

Normal
```
Game EXE <-> System XInput DLL
```
With Durazno
```
Game EXE <-> Durazno DLL <-> System XInput DLL
```
